uploads = []
generated = []

[[outputs]]
id = "jKGBTBhRGJL-LJ4SyLYcO"
uri = "file://ScreenGenie_MVP.zip"
type = "unspecified"
title = "ScreenGenie MVP — Complete Project + DB Dump"

[[outputs]]
id = "VnUNd-iAMo7aq2dNfDLZX"
uri = "file://PROJECT_DUMP.md"
type = "text"
title = "Full Architectural Manifest"
